CREATE TABLE IF NOT EXISTS `Checkbox_Feedback` (
  `uid` int(10) NOT NULL auto_increment,
  `DATE` timestamp NOT NULL default CURRENT_TIMESTAMP,
  `deviceID` text character set latin1 collate latin1_spanish_ci NOT NULL,
  `username` varchar(32) character set utf8 collate utf8_unicode_ci NOT NULL,
  `isChild` tinyint(1) NOT NULL,
  `screenName` varchar(32) character set utf8 collate utf8_unicode_ci NOT NULL,
  `customFeedback` text character set utf8 collate utf8_unicode_ci,
  `cb1` enum('TRUE','FALSE') default NULL,
  `cb2` enum('TRUE','FALSE') default NULL,
  `cb3` enum('TRUE','FALSE') default NULL,
  `cb4` enum('TRUE','FALSE') default NULL,
  `cb5` enum('TRUE','FALSE') default NULL,
  `cb6` enum('TRUE','FALSE') default NULL,
  `cb7` enum('TRUE','FALSE') default NULL,
  `cb8` enum('TRUE','FALSE') default NULL,
  `cb9` enum('TRUE','FALSE') default NULL,
  `cb10` enum('TRUE','FALSE') default NULL,
  `cb11` enum('TRUE','FALSE') default NULL,
  `cb12` enum('TRUE','FALSE') default NULL,
  `cb13` enum('TRUE','FALSE') default NULL,
  `cb14` enum('TRUE','FALSE') default NULL,
  `cb15` enum('TRUE','FALSE') default NULL,
  PRIMARY KEY  (`uid`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=19 ;