CREATE TABLE IF NOT EXISTS `Tasks_Feedback` (
  `uid` int(10) NOT NULL auto_increment,
  `DATE` timestamp NOT NULL default CURRENT_TIMESTAMP,
  `username` varchar(32) character set utf8 collate utf8_unicode_ci NOT NULL,
  `item1` text character set utf8 collate utf8_unicode_ci,
  `rating1` int(2) default NULL,
  `item2` text character set utf8 collate utf8_unicode_ci,
  `rating2` int(2) default NULL,
  `item3` text character set utf8 collate utf8_unicode_ci,
  `rating3` int(2) default NULL,
  `item4` text character set utf8 collate utf8_unicode_ci,
  `rating4` int(2) default NULL,
  `item5` text character set utf8 collate utf8_unicode_ci,
  `rating5` int(2) default NULL,
  `item6` text character set utf8 collate utf8_unicode_ci,
  `rating6` int(2) default NULL,
  `item7` text character set utf8 collate utf8_unicode_ci,
  `rating7` int(2) default NULL,
  `item8` text character set utf8 collate utf8_unicode_ci,
  `rating8` int(2) default NULL,
  `item9` text character set utf8 collate utf8_unicode_ci,
  `rating9` int(2) default NULL,
  `item10` text character set utf8 collate utf8_unicode_ci,
  `rating10` int(2) default NULL,
  PRIMARY KEY  (`uid`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;
